# Production environment values
replicaCount: 5

image:
  tag: "stable"
  pullPolicy: IfNotPresent

container:
  env:
    FLASK_ENV: production
    LOG_LEVEL: WARNING
    DEBUG: "false"

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

healthCheck:
  livenessProbe:
    initialDelaySeconds: 90
    periodSeconds: 30
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10

ingress:
  enabled: true
  hosts:
    - host: api.yourdomain.com
      paths:
        - path: /
          pathType: Prefix

service:
  nodePort:
    enabled: false
