# Default values for microservice-a
# This is a YAML-formatted file.

# Image configuration
image:
  repository: ghcr.io/sznaskme/microservice-a/orders
  tag: latest
  pullPolicy: Always

# Image pull secrets
imagePullSecrets:
  - name: ghcr-secret

# Service account
serviceAccount:
  create: false
  name: ""

# Pod configuration
replicaCount: 3

# Container configuration
container:
  port: 5000
  env:
    FLASK_ENV: production
    PORT: "5000"
    WORKERS: "4"
    DEBUG: "false"
    LOG_LEVEL: "INFO"
    HEALTH_CHECK_ENABLED: "true"
    METRICS_ENABLED: "true"

# Resource limits
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Health checks
healthCheck:
  enabled: true
  path: /health
  port: 5000
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  
  # NodePort service (for external access)
  nodePort:
    enabled: true
    port: 30000

# ConfigMap configuration
configMap:
  enabled: true
  data:
    FLASK_ENV: production
    LOG_LEVEL: WARNING
    DEBUG: "false"
    HOST: "0.0.0.0"
    PORT: "5000"
    WORKERS: "4"
    METRICS_ENABLED: "true"
    HEALTH_CHECK_ENABLED: "true"

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Ingress configuration
ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: microservice-a-tls
      hosts:
        - api.yourdomain.com

# Pod labels and annotations
podLabels: {}
podAnnotations: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Security context
securityContext: {}
podSecurityContext: {}

# Namespace
namespace: default
